version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-bot
    ports:
      - "127.0.0.1:8080:8080"  # Accessible only on localhost
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"  # Expose to the outside world on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - trading-bot
    restart: unless-stopped
