version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-bot
    ports:
      - "80:80"
    env_file:
      - .env
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "80"]
    restart: unless-stopped
