version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading-bot
    ports:
      - "127.0.0.1:8080:8080"  # Accessible only on localhost
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - trading_bot_db:/app/database
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped

volumes:
  trading_bot_db:
    name: trading_bot_db
